# Generated by Django 4.0.5 on 2022-06-15 05:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
